### 1. 사용자 생성
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "피카츄",
  "age" : 25
}

###

### 2. 수정
PUT http://localhost:8080/users/1
Content-Type: application/json

{
  "name" : "라이츄",
  "age" : 26
}

###

### 3. 삭제
DELETE http://localhost:8080/user/1